# version: "3"
# services:
#   redis: 
#     image: redis:latest
#     restart: unless-stopped
#   app:
#     depends_on:
#       - redis
#     build:
#       context: .
#       dockerfile: Dockerfile
#     restart: on-failure
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app

# version: '3'
# services:
#   app: 
#     container_name: server
#     build: ./
#     command: npm start
#     working_dir: /usr/src/server
#     environment:
#       - REDIS_URI=redis://redis:6379
#     links:
#       - redis
#     ports: 
#       - "8000:8000"
#     volumes:
#       - ./:/usr/src/server

#   redis: 
#     image: redis
#     ports: 
#       - "6379:6379"

version: '3'

services:
  #postgres
  postgres:
    build: ./src/postgres
    environment:
      POSTGRES_USER: ruona
      POSTGRES_PASSWORD: aTopTradeFX
      POSTGRES_DB: aTopTrade
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
  #redis
  redis:
    image: redis
    ports:
      - "6379:6378"
    command: redis-server
    #backend api
  web:
    build: ./
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      # REDIS_URI: redis://redis:6379
      POSTGRES_URI: postgres://ruona:aTopTradeFX@postgres:5432/aTopTrade
    links:
      - postgres
    command: npm start
