version: '3'

services:
  #postgres
  postgres:
    build: ./src/postgres
    environment:
      POSTGRES_USER: ruona
      POSTGRES_PASSWORD: aTopTradeFX
      POSTGRES_DB: aTopTrade
      POSTGRES_HOST: postgres
    volumes:
      - /var/lib/docker/volumes/postgres
    ports:
      - "5432:5432"

  #redis
  redis:
    image: redis
    ports:
      - "6379:6378"
    command: redis-server
    #backend api
  web:
    build: ./
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      # REDIS_URI: redis://redis:6379
      POSTGRES_URI: postgres://ruona:aTopTradeFX@postgres:5432/aTopTrade
    links:
      - postgres
    command: npm start
